version: '3'

services:
  frontend: 
    build: ./teste-3-frontend
    container_name: react
    ports: 
      - 3000:3000
    volumes: 
      - ./teste-3-frontend:/usr/app
  backend:
    build: ./teste-2-backend
    container_name: nodejs
    restart: always
    ports:
      - 3333:3333
    volumes:
      - ./teste-2-backend:/usr/app
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bravi_db
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./teste-2-backend/mysql:/var/lib/mysql